# Generated by Django 4.1.7 on 2023-03-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_product_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='image',
        ),
        migrations.AddField(
            model_name='product_image',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.CharField(max_length=100),
        ),
    ]
