# Generated by Django 4.1.7 on 2023-03-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_orderitem_order_delete_order'),
        ('myapp', '0023_alter_order_phone'),
    ]

    operations = [
    ]
