# Generated by Django 4.1.7 on 2023-03-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_product_image_image_url_product_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(upload_to='media/ftd_img'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
    ]
