# Generated by Django 4.1.7 on 2023-03-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_product_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product_image',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
