# Generated by Django 4.1.7 on 2023-03-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_remove_product_image_image_product_image_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
